http:
  mappers:
    json-pretty-print: true
    json-sort-keys: true

app:
  development: true
spring:
  jpa:
    properties:
      hibernate:
        dialect: com.mavenir.vmp.core.jpa.SQLiteDialect

